// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiNgpn2PNYixpuH6-G4YGXt-BZiLcxLN0',
    appId: '1:117751649162:web:e9cdabb659ad197eb2ee73',
    messagingSenderId: '117751649162',
    projectId: 'easy-wallet-a4420',
    authDomain: 'easy-wallet-a4420.firebaseapp.com',
    storageBucket: 'easy-wallet-a4420.firebasestorage.app',
    measurementId: 'G-LPKPQ1F7DX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXMMRbQkyNZ-YR3iBb8MjKIQASA3RJ_Zg',
    appId: '1:117751649162:android:20a5c2cef5b47818b2ee73',
    messagingSenderId: '117751649162',
    projectId: 'easy-wallet-a4420',
    storageBucket: 'easy-wallet-a4420.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoAtn4HHqhoPhfFfG3QJ4XHyPcUqp8V-o',
    appId: '1:117751649162:ios:1e0cf5d0622a06e6b2ee73',
    messagingSenderId: '117751649162',
    projectId: 'easy-wallet-a4420',
    storageBucket: 'easy-wallet-a4420.firebasestorage.app',
    iosBundleId: 'com.example.easyWalletApp',
  );
}
